apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    service.type: instrumentation
  labels:
    io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
        service.type: instrumentation
      labels:
        io.kompose.service: loki
    spec:
      containers:
        - image: grafana/loki:3.4.3@sha256:5fe9fa99e9a747297cdf0239a5b25d192d8f668bd6505b09beef4dffcab5aac2
          name: loki
          ports:
            - containerPort: 3100
              protocol: TCP
      restartPolicy: Always
