apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    service.type: instrumentation
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
        service.type: instrumentation
      labels:
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file=/etc/tempo.yaml
          image: grafana/tempo:2.9.0@sha256:65a5789759435f1ef696f1953258b9bbdb18eb571d5ce711ff812d2e128288a4
          name: tempo
          ports:
            - containerPort: 3200
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/tempo.yaml
              name: tempo-cm0
              subPath: tempo.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: local-tempo.yaml
                path: tempo.yaml
            name: tempo-cm0
          name: tempo-cm0
