apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    service.type: application
  labels:
    io.kompose.service: quickpizza
  name: quickpizza
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quickpizza
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
        service.type: application
      labels:
        io.kompose.service: quickpizza
    spec:
      containers:
        - env:
            - name: QUICKPIZZA_ENABLE_ALL_SERVICES
              value: "1"
            - name: QUICKPIZZA_OTEL_SERVICE_INSTANCE_ID
              value: quickpizza
            - name: QUICKPIZZA_OTEL_SERVICE_NAME
              value: quickpizza
            - name: QUICKPIZZA_OTLP_ENDPOINT
              value: http://alloy:4318
            - name: QUICKPIZZA_TRUST_CLIENT_TRACEID
              value: "1"
          image: ghcr.io/grafana/quickpizza-local:latest@sha256:b650ce8f443800fe5625339d7f3e2521fd58af9a89c3019b843fa5710787af59
          name: quickpizza
          ports:
            - containerPort: 3333
              protocol: TCP
      restartPolicy: Always
