apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f compose.grafana-local-stack.monolithic.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    service.type: application
  labels:
    io.kompose.service: quickpizza
  name: quickpizza
spec:
  type: LoadBalancer
  ports:
    - name: "3333"
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: quickpizza
